# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyNews
  pod 'RealmSwift', '~> 3.13'
'
  target 'EasyNewsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift', '~> 3.13'
  end

  target 'EasyNewsUITests' do
    # Pods for testing
    pod 'RealmSwift', '~> 3.13'
  end
end
